exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("candidates")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("candidates").insert([
        {
          name: "عائشة سالم",
          city: "عمان",
          list: "قائمة أ",
          circle: "الدائرة الثانية",
          party: "حزب أ",
          circle_list: "قائمة الدائرة الثانية",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "كوتا",
          isActivate: true,
          candidate_national_id: 100017,
          party_votes: 0,
        },
        {
          name: "علي رحمن",
          city: "إربد",
          list: "قائمة ب",
          circle: "الدائرة الثالثة",
          party: "حزب ب",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          candidate_national_id: 100018,
        },
        {
          name: "سامية أحمد",
          city: "الزرقاء",
          list: "قائمة ج",
          circle: "الدائرة الأولى",
          party: "حزب ج",
          circle_list: "قائمة الدائرة الأولى",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "مسيحي",
          isActivate: true,
          candidate_national_id: 100019,
        },
        {
          name: "خالد محمد",
          city: "عمان",
          list: "قائمة د",
          circle: "الدائرة الثانية",
          party: "حزب د",
          circle_list: "قائمة الدائرة الثانية",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "شيشاني",
          isActivate: true,
          candidate_national_id: 100020,
        },
        {
          name: "ماروى نبيل",
          city: "الزرقاء",
          list: "قائمة ه",
          circle: "الدائرة الأولى",
          party: "حزب ه",
          circle_list: "قائمة الدائرة الأولى",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "كوتا",
          isActivate: true,
          candidate_national_id: 100021,
        },
        {
          name: "طارق علي",
          city: "عمان",
          list: "قائمة و",
          circle: "الدائرة الثانية",
          party: "حزب و",
          circle_list: "قائمة الدائرة الثانية",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          candidate_national_id: 100022,
        },
        {
          name: "ليلى سعيد",
          city: "إربد",
          list: "قائمة ز",
          circle: "الدائرة الثالثة",
          party: "حزب ز",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "مسيحي",
          isActivate: true,
          candidate_national_id: 100023,
        },
        {
          name: "محمد حسين",
          city: "الزرقاء",
          list: "قائمة ح",
          circle: "الدائرة الأولى",
          party: "حزب ح",
          circle_list: "قائمة الدائرة الأولى",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "شيشاني",
          isActivate: true,
          candidate_national_id: 100024,
        },
        {
          name: "نوال خالد",
          city: "عمان",
          list: "قائمة ط",
          circle: "الدائرة الثانية",
          party: "حزب ط",
          circle_list: "قائمة الدائرة الثانية",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "كوتا",
          isActivate: true,
          candidate_national_id: 100025,
        },
        {
          name: "محمد ناصر",
          city: "إربد",
          list: "قائمة ي",
          circle: "الدائرة الثالثة",
          party: "حزب ي",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          candidate_national_id: 100026,
        },
        {
          name: "رها عبد الله",
          city: "الزرقاء",
          list: "قائمة ك",
          circle: "الدائرة الأولى",
          party: "حزب ك",
          circle_list: "قائمة الدائرة الأولى",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "مسيحي",
          isActivate: true,
          candidate_national_id: 100027,
        },
        {
          name: "خليل أحمد",
          city: "عمان",
          list: "قائمة ل",
          circle: "الدائرة الثانية",
          party: "حزب ل",
          circle_list: "قائمة الدائرة الثانية",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "شيشاني",
          isActivate: true,
          candidate_national_id: 100028,
        },
        {
          name: "أحمد صادق",
          city: "إربد",
          list: "قائمة م",
          circle: "الدائرة الثالثة",
          party: "حزب م",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "كوتا",
          isActivate: true,
          candidate_national_id: 100029,
        },
        {
          name: "نور أحمد",
          city: "الزرقاء",
          list: "قائمة ن",
          circle: "الدائرة الأولى",
          party: "حزب ن",
          circle_list: "قائمة الدائرة الأولى",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "مسلم",
          isActivate: true,
          candidate_national_id: 100030,
        },
        {
          name: "فادي أحمد",
          city: "عمان",
          list: "قائمة س",
          circle: "الدائرة الثانية",
          party: "حزب س",
          circle_list: "قائمة الدائرة الثانية",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسيحي",
          isActivate: true,
          candidate_national_id: 100031,
        },
        {
          name: "مريم جابر",
          city: "إربد",
          list: "قائمة ع",
          circle: "الدائرة الثالثة",
          party: "حزب ع",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "شيشاني",
          isActivate: true,
          candidate_national_id: 100032,
        },
        {
          name: "إبراهيم صالح",
          city: "الزرقاء",
          list: "قائمة ف",
          circle: "الدائرة الأولى",
          party: "حزب ف",
          circle_list: "قائمة الدائرة الأولى",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "كوتا",
          isActivate: true,
          candidate_national_id: 100033,
          party_votes: 0,
        },
        {
          name: "ناديا محمد",
          city: "عمان",
          list: "قائمة ق",
          circle: "الدائرة الثانية",
          party: "حزب ق",
          circle_list: "قائمة الدائرة الثانية",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "مسلم",
          isActivate: true,
          candidate_national_id: 100034,
          party_votes: 0,
        },
        {
          name: "وليد عبد الله",
          city: "إربد",
          list: "قائمة ر",
          circle: "الدائرة الثالثة",
          party: "حزب ر",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسيحي",
          isActivate: true,
          candidate_national_id: 100035,
        },
        {
          name: "فرح نبيل",
          city: "الزرقاء",
          list: "قائمة ش",
          circle: "الدائرة الأولى",
          party: "حزب ش",
          circle_list: "قائمة الدائرة الأولى",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "شيشاني",
          isActivate: true,
          candidate_national_id: 100036,
        },
        {
          name: "حسن علي",
          city: "عمان",
          list: "قائمة ت",
          circle: "الدائرة الثانية",
          party: "حزب ت",
          circle_list: "قائمة الدائرة الثانية",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "كوتا",
          isActivate: true,
          candidate_national_id: 100037,
        },
        {
          name: "هالة عبد الله",
          city: "إربد",
          list: "قائمة ث",
          circle: "الدائرة الثالثة",
          party: "حزب ث",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "مسلم",
          isActivate: true,
          candidate_national_id: 100038,
        },
        {
          name: "سامي ناصر",
          city: "الزرقاء",
          list: "قائمة ج",
          circle: "الدائرة الأولى",
          party: "حزب ج",
          circle_list: "قائمة الدائرة الأولى",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسيحي",
          isActivate: true,
          candidate_national_id: 100039,
        },
        {
          name: "ندى زكريا",
          city: "عمان",
          list: "قائمة خ",
          circle: "الدائرة الثانية",
          party: "حزب خ",
          circle_list: "قائمة الدائرة الثانية",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "شيشاني",
          isActivate: true,
          candidate_national_id: 100040,
        },
      ]);
    });
};
