exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return knex('users').insert([
        {
          "national_id": 2000000001,
          "email": "email1@gmail.com",
          "name": "سليم علي عبد الرحمن الجبري",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "g",
          "role": "voter",
          "isApproved": false,
          "Whitepaper": null,
          "type": "مسلم",
          "gender": "male",
          "isActivate": true,
          "otp": null
      },
      {
        "national_id": 100037,
        "email": "khaled.mohamed@example.com",
        "name": "خالد محمد",
        "city": "عمان",
        "circle": "الدائرة الثانية",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "hashedpassword37",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "كوتا",
        "gender": "male",
        "isActivate": true,
        "otp": null
      },
      {
          "national_id": 2000000002,
          "email": "email2@gmail.com",
          "name": "محمود علي عبد الله الشيشاني",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "",
          "role": "voter",
          "isApproved": false,
          "Whitepaper": null,
          "type": "شيشاني",
          "gender": "male",
          "isActivate": true,
          "otp": null
      },
      {
          "national_id": 2000000003,
          "email": "email1113@gmail.com",
          "name": "نور أحمد محمود",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "",
          "role": "voter",
          "isApproved": false,
          "Whitepaper": null,
          "type": "مسيحي",
          "gender": "female",
          "isActivate": true,
          "otp": null
      },
      {
          "national_id": 2000000004,
          "email": "emai00l4@gmail.com",
          "name": "فاطمة خالد عبد الله",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "",
          "role": "voter",
          "isApproved": false,
          "Whitepaper": null,
          "type": "مسلم",
          "gender": "female",
          "isActivate": true,
          "otp": null
      },
      {
          "national_id": 2000000005,
          "email": "email5@gmail.com",
          "name": "عبد الله حسين محمد",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "",
          "role": "voter",
          "isApproved": false,
          "Whitepaper": null,
          "type": "مسلم",
          "gender": "male",
          "isActivate": true,
          "otp": null
      },
      {
          "national_id": 2000000006,
          "email": "email6@gmail.com",
          "name": "ريم محمد عبد العزيز",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "",
          "role": "candidate",
          "isApproved": false,
          "Whitepaper": null,
          "type": "مسيحي",
          "gender": "female",
          "isActivate": true,
          "otp": null
      },
      {
          "national_id": 2000000007,
          "email": "email7@gmail.com",
          "name": "سامي يوسف الشيشاني",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "",
          "role": "voter",
          "isApproved": false,
          "Whitepaper": null,
          "type": "شيشاني",
          "gender": "male",
          "isActivate": true,
          "otp": null
      },
      {
          "national_id": 2000000008,
          "email": "email8@gmail.com",
          "name": "أمينة محمد الكوتا",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "",
          "role": "voter",
          "isApproved": false,
          "Whitepaper": null,
          "type": "كوتا",
          "gender": "female",
          "isActivate": true,
          "otp": null
      },
      {
          "national_id": 2000000009,
          "email": "email9@gmail.com",
          "name": "يوسف علي الكوتا",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "",
          "role": "voter",
          "isApproved": false,
          "Whitepaper": null,
          "type": "كوتا",
          "gender": "male",
          "isActivate": true,
          "otp": null
      },
      {
          "national_id": 2000000010,
          "email": "email10@gmail.com",
          "name": "علي أحمد الجبري",
          "city": "الزرقاء",
          "circle": "الدائرة الأولى",
          "isVotedcircle": false,
          "isVotedparty": false,
          "password": "",
          "role": "voter",
          "isApproved": false,
          "Whitepaper": null,
          "type": "مسلم",
          "gender": "male",
          "isActivate": true,
          "otp": null
      },
      {
        "national_id": 2000000011,
        "email": "email11@gmail.com",
        "name": "خالد علي الصالح",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "مسلم",
        "gender": "male",
        "isActivate": true,
        "otp": null
    },
    {
        "national_id": 2000000012,
        "email": "email12@gmail.com",
        "name": "حنان محمد الشيشاني",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "شيشاني",
        "gender": "female",
        "isActivate": true,
        "otp": null
    },
    {
        "national_id": 2000000013,
        "email": "email13@gmail.com",
        "name": "زياد أحمد المطارنة",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "مسيحي",
        "gender": "male",
        "isActivate": true,
        "otp": null
    },
    {
        "national_id": 2000000014,
        "email": "email14@gmail.com",
        "name": "عبير علي عبد الرحمن",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "مسلم",
        "gender": "female",
        "isActivate": true,
        "otp": null
    },
    {
        "national_id": 2000000015,
        "email": "email15@gmail.com",
        "name": "محمد زياد القيسي",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "مسلم",
        "gender": "male",
        "isActivate": true,
        "otp": null
    },
    {
        "national_id": 2000000016,
        "email": "email16@gmail.com",
        "name": "ليلى أحمد حسن",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "مسيحي",
        "gender": "female",
        "isActivate": true,
        "otp": null
    },
    {
        "national_id": 2000000017,
        "email": "email17@gmail.com",
        "name": "يوسف خالد أبو شندي",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "شيشاني",
        "gender": "male",
        "isActivate": true,
        "otp": null
    },
    {
        "national_id": 2000000018,
        "email": "email18@gmail.com",
        "name": "أمل زياد الشيشاني",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "شيشاني",
        "gender": "female",
        "isActivate": true,
        "otp": null
    },
    {
        "national_id": 2000000019,
        "email": "email19@gmail.com",
        "name": "عبد الرحمن كمال الجبري",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "مسلم",
        "gender": "male",
        "isActivate": true,
        "otp": null
    },
    {
        "national_id": 2000000020,
        "email": "email20@gmail.com",
        "name": "مها علي الكوتا",
        "city": "الزرقاء",
        "circle": "الدائرة الأولى",
        "isVotedcircle": false,
        "isVotedparty": false,
        "password": "",
        "role": "voter",
        "isApproved": false,
        "Whitepaper": null,
        "type": "كوتا",
        "gender": "female",
        "isActivate": true,
        "otp": null
    },
    {
      "national_id": 2000000021,
      "email": "email21@gmail.com",
      "name": "زياد محمد الصالح",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "مسلم",
      "gender": "male",
      "isActivate": true,
      "otp": null
  },
  {
      "national_id": 2000000022,
      "email": "email22@gmail.com",
      "name": "سعاد علي الكوتا",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "كوتا",
      "gender": "female",
      "isActivate": true,
      "otp": null
  },
  {
      "national_id": 2000000023,
      "email": "email23@gmail.com",
      "name": "باسل أحمد المطارنة",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "مسيحي",
      "gender": "male",
      "isActivate": true,
      "otp": null
  },
  {
      "national_id": 2000000024,
      "email": "email24@gmail.com",
      "name": "مها خالد الجبري",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "مسلم",
      "gender": "female",
      "isActivate": true,
      "otp": null
  },
  {
      "national_id": 2000000025,
      "email": "email25@gmail.com",
      "name": "سليم علي الشيشاني",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "شيشاني",
      "gender": "male",
      "isActivate": true,
      "otp": null
  },
  {
      "national_id": 2000000026,
      "email": "email26@gmail.com",
      "name": "هدى علي المطارنة",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "مسيحي",
      "gender": "female",
      "isActivate": true,
      "otp": null
  },
  {
      "national_id": 2000000027,
      "email": "email27@gmail.com",
      "name": "أحمد محمد الكوتا",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "كوتا",
      "gender": "male",
      "isActivate": true,
      "otp": null
  },
  {
      "national_id": 2000000028,
      "email": "email28@gmail.com",
      "name": "ليلى خالد الشيشاني",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "شيشاني",
      "gender": "female",
      "isActivate": true,
      "otp": null
  },
  {
      "national_id": 2000000029,
      "email": "email29@gmail.com",
      "name": "عمر أحمد الكوتا",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "كوتا",
      "gender": "male",
      "isActivate": true,
      "otp": null
  },
  {
      "national_id": 2000000030,
      "email": "email30@gmail.com",
      "name": "نورا زياد الشيشاني",
      "city": "الزرقاء",
      "circle": "الدائرة الأولى",
      "isVotedcircle": false,
      "isVotedparty": false,
      "password": "",
      "role": "voter",
      "isApproved": false,
      "Whitepaper": null,
      "type": "شيشاني",
      "gender": "female",
      "isActivate": true,
      "otp": null
  },
  {
    "national_id": 2000000031,
    "email": "email31@gmail.com",
    "name": "محمود علي الجبري",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسلم",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000032,
    "email": "email32@gmail.com",
    "name": "فاطمة زياد الكوتا",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "كوتا",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000033,
    "email": "email33@gmail.com",
    "name": "خالد أحمد الشيشاني",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "شيشاني",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000034,
    "email": "email34@gmail.com",
    "name": "نادية علي المطارنة",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسيحي",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000035,
    "email": "email35@gmail.com",
    "name": "زياد محمد الجبري",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسلم",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000036,
    "email": "email36@gmail.com",
    "name": "هدى علي الجبري",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسلم",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000037,
    "email": "email37@gmail.com",
    "name": "أحمد خالد الكوتا",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "كوتا",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000038,
    "email": "email38@gmail.com",
    "name": "ليلى زياد الشيشاني",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "شيشاني",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000039,
    "email": "email39@gmail.com",
    "name": "سالم علي المطارنة",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسيحي",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000040,
    "email": "emaial40@gmail.com",
    "name": "نور علي الجبري",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسلم",
    "gender": "female",
    "isActivate": true,
    "otp": null
  },
  {
    "national_id": 2000000041,
    "email": "email41@gmail.com",
    "name": "مروان زياد الشيشاني",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "شيشاني",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000042,
    "email": "email42@gmail.com",
    "name": "سمر خالد المطارنة",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسيحي",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000043,
    "email": "email43@gmail.com",
    "name": "علي محمد الجبري",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسلم",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000044,
    "email": "email44@gmail.com",
    "name": "هناء زياد الكوتا",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "كوتا",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000045,
    "email": "email45@gmail.com",
    "name": "يوسف أحمد الشيشاني",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "شيشاني",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000046,
    "email": "email46@gmail.com",
    "name": "ليلى علي الجبري",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسلم",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000047,
    "email": "email47@gmail.com",
    "name": "خالد زياد المطارنة",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسيحي",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000048,
    "email": "email48@gmail.com",
    "name": "سميرة علي الكوتا",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "كوتا",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000049,
    "email": "email49@gmail.com",
    "name": "أحمد محمد الشيشاني",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "شيشاني",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000050,
    "email": "email50@gmail.com",
    "name": "سعاد علي المطارنة",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسيحي",
    "gender": "female",
    "isActivate": true,
    "otp": null
  },
  {
    "national_id": 2000000051,
    "email": "email51@gmail.com",
    "name": "أحمد زياد الكوتا",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "كوتا",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000052,
    "email": "email52@gmail.com",
    "name": "ليلى أحمد الشيشاني",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "شيشاني",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000053,
    "email": "email53@gmail.com",
    "name": "خالد علي الجبري",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسلم",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000054,
    "email": "email54@gmail.com",
    "name": "سمر زياد المطارنة",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسيحي",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000055,
    "email": "email55@gmail.com",
    "name": "يوسف محمد الكوتا",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "كوتا",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000056,
    "email": "email56@gmail.com",
    "name": "هدى علي الشيشاني",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "شيشاني",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000057,
    "email": "email57@gmail.com",
    "name": "خالد أحمد الجبري",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسلم",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000058,
    "email": "email58@gmail.com",
    "name": "ليلى خالد المطارنة",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "مسيحي",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000059,
    "email": "email59@gmail.com",
    "name": "سالم زياد الشيشاني",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "شيشاني",
    "gender": "male",
    "isActivate": true,
    "otp": null
},
{
    "national_id": 2000000060,
    "email": "email60@gmail.com",
    "name": "نادية علي الكوتا",
    "city": "الزرقاء",
    "circle": "الدائرة الأولى",
    "isVotedcircle": false,
    "isVotedparty": false,
    "password": "",
    "role": "voter",
    "isApproved": false,
    "Whitepaper": null,
    "type": "كوتا",
    "gender": "female",
    "isActivate": true,
    "otp": null
},
{
  "national_id": 2000000061,
  "email": "email61@gmail.com",
  "name": "أحمد علي الجبري",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": false,
  "isVotedparty": false,
  "password": "",
  "role": "voter",
  "isApproved": false,
  "Whitepaper": null,
  "type": "مسلم",
  "gender": "male",
  "isActivate": true,
  "otp": null
},
{
  "national_id": 2000000062,
  "email": "email62@gmail.com",
  "name": "فاطمة زياد الشيشاني",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": false,
  "isVotedparty": false,
  "password": "",
  "role": "voter",
  "isApproved": false,
  "Whitepaper": null,
  "type": "شيشاني",
  "gender": "female",
  "isActivate": true,
  "otp": null
},
{
  "national_id": 2000000063,
  "email": "email63@gmail.com",
  "name": "خالد زياد المطارنة",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": false,
  "isVotedparty": false,
  "password": "",
  "role": "voter",
  "isApproved": false,
  "Whitepaper": null,
  "type": "مسيحي",
  "gender": "male",
  "isActivate": true,
  "otp": null
},
{
  "national_id": 2000000064,
  "email": "email64@gmail.com",
  "name": "ليلى أحمد الكوتا",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": false,
  "isVotedparty": false,
  "password": "",
  "role": "voter",
  "isApproved": false,
  "Whitepaper": null,
  "type": "كوتا",
  "gender": "female",
  "isActivate": true,
  "otp": null
},
{
  "national_id": 2000000065,
  "email": "email65@gmail.com",
  "name": "سالم علي الجبري",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": false,
  "isVotedparty": false,
  "password": "",
  "role": "voter",
  "isApproved": false,
  "Whitepaper": null,
  "type": "مسلم",
  "gender": "male",
  "isActivate": true,
  "otp": null
},
{
  "national_id": 2000000066,
  "email": "email66@gmail.com",
  "name": "سعاد زياد المطارنة",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": false,
  "isVotedparty": false,
  "password": "",
  "role": "voter",
  "isApproved": false,
  "Whitepaper": null,
  "type": "مسيحي",
  "gender": "female",
  "isActivate": true,
  "otp": null
},
{
  "national_id": 2000000067,
  "email": "email67@gmail.com",
  "name": "خالد علي الكوتا",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": false,
  "isVotedparty": false,
  "password": "",
  "role": "voter",
  "isApproved": false,
  "Whitepaper": null,
  "type": "كوتا",
  "gender": "male",
  "isActivate": true,
  "otp": null
},
{
  "national_id": 2000000068,
  "email": "email68@gmail.com",
  "name": "هدى زياد الشيشاني",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": true,
  "isVotedparty": false,
  "password": "",
  "role": "voter",
  "isApproved": false,
  "Whitepaper": null,
  "type": "شيشاني",
  "gender": "female",
  "isActivate": true,
  "otp": null
},
{
  "national_id": 2000000069,
  "email": "email69@gmail.com",
  "name": "يوسف علي الجبري",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": true,
  "isVotedparty": false,
  "password": "",
  "role": "voter",
  "isApproved": false,
  "Whitepaper": null,
  "type": "مسلم",
  "gender": "male",
  "isActivate": true,
  "otp": null
},
{
  "national_id": 2000000070,
  "email": "email70@gmail.com",
  "name": "نادية زياد المطارنة",
  "city": "الزرقاء",
  "circle": "الدائرة الأولى",
  "isVotedcircle": true,
  "isVotedparty": false,
  "password": "",
  "role": "candidate",
  "isApproved": false,
  "Whitepaper": null,
  "type": "مسيحي",
  "gender": "female",
  "isActivate": true,
  "otp": null
}
      ]);
    });
};
